# Generated by Django 5.0 on 2024-12-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
